# Generated by Django 5.0.2 on 2026-04-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('auditor', 'Аудитор')], default='operator', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
